import 'dart:math';
import '../models/candidate_model.dart';

/// Sample AI-based Candidate Scoring Service for ScreenerPro Showcase.
/// Includes logic for resume parsing, keyword matching, and experience analysis.
class CandidateScoringService {
  final Random _random = Random();

  /// Simulates AI-based resume analysis and returns a CandidateModel with scores.
  Future<CandidateModel> analyzeCandidate(String resumeText, List<String> requiredSkills) async {
    // Artificial delay to simulate complex AI processing
    await Future.delayed(const Duration(seconds: 3));

    // Sample logic for keyword matching score
    double skillScore = _calculateSkillMatch(resumeText, requiredSkills);
    
    // Sample logic for experience analysis (mocked)
    double experienceScore = 70 + _random.nextInt(30).toDouble();

    // Final Weighted Average Score
    double finalScore = (skillScore * 0.6) + (experienceScore * 0.4);

    return CandidateModel(
      id: 'C-${_random.nextInt(99999)}',
      name: 'Simulated Candidate Name',
      skillMatchScore: skillScore,
      experienceScore: experienceScore,
      finalScore: finalScore,
      recommendation: _getRecommendation(finalScore),
      resumeSummary: 'Summary generated by ScreenerPro AI engine based on analyzed text.',
    );
  }

  double _calculateSkillMatch(String resumeText, List<String> requiredSkills) {
    if (requiredSkills.isEmpty) return 100.0;
    
    int matchCount = 0;
    for (var skill in requiredSkills) {
      if (resumeText.toLowerCase().contains(skill.toLowerCase())) {
        matchCount++;
      }
    }
    return (matchCount / requiredSkills.length) * 100.0;
  }

  String _getRecommendation(double finalScore) {
    if (finalScore >= 85) return 'Highly Recommended';
    if (finalScore >= 70) return 'Good Fit';
    if (finalScore >= 50) return 'Potential Review';
    return 'Not Recommended';
  }
}
